version: 2.1
executors:
  node-executor: 
    docker:
      - image: circleci/node:10
commands:
  build-and-test:
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache: 
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: 
          name: run tests
          command: yarn run test
      - run: 
          name: Gatsby Build
          command: yarn run build
workflows:
    version: 2
    build-deploy:
      jobs:
        - build: 
            filters:
              branches: 
                ignore: 
                  - master
        - release: 
            filters:
              branches:
                only:
                  - master
jobs: 
  build:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - build-and-test
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - build-and-test