commands:
  build-and-test:
    executors:
      node-executor:
      docker:
        - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache: 
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: 
          name: run tests
          command: yarn run test
      - run: 
          name: Gatsby Build
          command: yarn run build
version: 2.1
orbs:
  node: circleci/node@3.0.1
workflows:
    build-and-test:
      jobs:
        - build-and-test