version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          command: yarn run test
          name: run YARN tests
workflows:
    build-and-test:
      jobs:
        - build-and-test