jobs:
  build-and-test:
    executor:
      name: node/default
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          name: run YARN tests
          command: yarn run test
      - run: 
          name: Gatsby Build
          command: yarn run build
version: 2.1
orbs:
  node: circleci/node@3.0.1
workflows:
    build-and-test:
      jobs:
        - build-and-test